version: 2.1
orbs:
  node: circleci/node@5
jobs:
  build:
    executor: node/default
    steps:
      - checkout
      - run: echo "Building things..."

  unit_tests:
    executor: node/default
    environment:
      JEST_JUNIT_OUTPUT_DIR: ./test-results/
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npm install jest-junit
      - run:
          name: Run tests
          command: npm run test:ci
      - store_test_results:
          path: ./test-results/

  deploy_dev:
    executor: node/default
    steps:
      - checkout
      - run: echo "Deploying to development environment..."

  deploy_prod:
    executor: node/default
    steps:
      - checkout
      - run: echo "Deploying to production environment..."

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build
      - unit_tests:
          requires:
            - build
      - deploy_dev:
          requires:
            - unit_tests
          filters:
            branches:
              only:
                - lesson
      - deploy_prod:
          requires:
            - unit_tests
          filters:
            branches:
              only:
                - main
