version: 2.1
orbs:
  node: circleci/node@5
jobs:
  install_dependencies:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - persist_to_workspace:
          root: .
          paths:
            - node_modules

  check_linter:
    executor: node/default
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Run formatter
          command: npm run prettier:w
      - run:
          name: Run linter
          command: npm run eslint:ci

  unit_tests:
    executor: node/default
    environment:
      JEST_JUNIT_OUTPUT_DIR: ./test-results/
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          command: npm install jest-junit
      - run:
          name: Run API tests
          command: npm run test:api
      #      - run:
      #          name: Run UI tests
      #          command: npm run test:ui
      - run:
          name: Run coverage
          command: npm run test:coverage
      - store_test_results:
          path: ./test-results/

  build:
    executor: node/default
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Run build
          command: npm run build

workflows:
  version: 2
  build-and-test:
    jobs:
       - install_dependencies
       - check_linter:
           requires:
             - install_dependencies
       - unit_tests:
           requires:
             - check_linter
       - build:
           requires:
             - unit_tests
#      - deploy:
#          requires:
#            - tests
#          when: on_success
