version: 2.1
orbs:
  node: circleci/node@5
jobs:
  build:
    executor: node/default
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - node/install-packages:
          pkg-manager: npm
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Run formatter
          command: npm run prettier:w
      - run:
          name: Run linter
          command: npm run eslint:ci
      - run:
          name: Run build
          command: npm run build
      - persist_to_workspace:
          root: .next
          paths:
            - .next
      - store_artifacts:
          path: .next

  tests:
    executor: node/default
    environment:
      JEST_JUNIT_OUTPUT_DIR: ./test-results/
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npm install jest-junit
      - run:
          name: Run API tests
          command: npm run test:api
      #      - run:
      #          name: Run UI tests
      #          command: npm run test:ui
      - run:
          name: Run coverage
          command: npm run test:coverage
      - store_test_results:
          path: ./test-results/

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - tests:
          requires:
            - build
#      - deploy:
#          requires:
#            - tests
#          when: on_success
