version: 2.1
orbs:
  node: circleci/node@5
jobs:
  # First job declared is for building things..
  build:
    executor: node/default
    steps:
      - checkout
      - run: echo "Building things..."
  # Second job declared is for launching unit tests with Jest
  unit-tests:
    executor: node/default
    environment:
      JEST_JUNIT_OUTPUT_DIR: ./test-results/
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npm install jest-junit
      - run:
          name: Run tests
          command: npm run test:ci
      - store_test_results:
          path: ./test-results/
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - unit-tests:
          requires:
            - build
