version: 2.1
orbs:
  node: circleci/node@5
jobs:
  prepare:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Run prettier
          command: npm run prettier:w
      - run:
          name: Run linter
          command: npm run eslint:ci

  build:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Run build
          command: npm run build

  tests:
    executor: node/default
    environment:
      JEST_JUNIT_OUTPUT_DIR: ./test-results/
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npm install jest-junit
      - run:
          name: Run API tests
          command: npm run test:api
#      - run:
#          name: Run UI tests
#          command: npm run test:ui
      - run:
          name: Run coverage
          command: npm run test:coverage
      - store_test_results:
          path: ./test-results/

workflows:
  version: 2
  build-and-test:
    jobs:
      - prepare
      - build
      - tests:
          requires:
            - build
#      - deploy:
#          requires:
#            - tests
#          when: on_success
